'use client';

import React, { useState } from 'react';
import { AIPromptEmptyState } from './AIPromptEmptyState';
import { AIChatInterface } from './AIChatInterface';
import { AIMessage, AIModel } from '@/types/ai';
import UserHeader from '@/components/ui/UserHeader';

export function AICodeGenContainer() {
  const [messages, setMessages] = useState<AIMessage[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedModel, setSelectedModel] = useState<AIModel>('Thalorix-X Vision');

  const handleGenerate = async (prompt: string, model: AIModel) => {
    const userMessage: AIMessage = {
      id: Date.now().toString(),
      role: 'user',
      content: prompt,
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, userMessage]);
    setSelectedModel(model);
    setIsGenerating(true);

    await new Promise((resolve) => setTimeout(resolve, 1500));

    let responseContent = '';
    let isCode = false;
    let language = 'javascript';

    const lowerPrompt = prompt.toLowerCase();

    if (lowerPrompt.includes('python') || lowerPrompt.includes('email validator')) {
      isCode = true;
      language = 'python';
      responseContent = `import re

def is_valid_email(email):
    """
    Validates an email address using regex.
    """
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$'
    return bool(re.match(pattern, email))

# Example usage
print(is_valid_email("test@example.com")) # True
print(is_valid_email("invalid-email")) # False`;
    } else if (lowerPrompt.includes('html') || lowerPrompt.includes('navbar')) {
      isCode = true;
      language = 'html';
      responseContent = `<nav class="navbar">
  <div class="container">
    <div class="brand">Brand</div>
    
    <!-- Mobile menu button -->
    <button class="menu-toggle">
      <svg width="24" height="24" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7" />
      </svg>
    </button>
    
    <!-- Desktop menu -->
    <div class="nav-links">
      <a href="#">Home</a>
      <a href="#">About</a>
      <a href="#">Contact</a>
    </div>
  </div>
</nav>`;
    } else if (lowerPrompt.includes('node') || lowerPrompt.includes('express')) {
      isCode = true;
      language = 'javascript';
      responseContent = `// Generated by Thalorix-X Vision

function solution(input) {
  // Parsing and validation
  if (!input) throw new Error("Input required");
  
  const items = Array.isArray(input) ? input : [input];
  
  return items
    .filter(Boolean)
    .map((item, i) => ({
      id: i + 1,
      value: item
    }));
}

console.log(solution(["apple", null, "banana"]));`;
    } else {
      isCode = true;
      language = 'javascript';
      responseContent = `// Generated by Thalorix-X Vision

function solution(input) {
  // Parsing and validation
  if (!input) throw new Error("Input required");
  
  const items = Array.isArray(input) ? input : [input];
  
  return items
    .filter(Boolean)
    .map((item, i) => ({
      id: i + 1,
      value: item
    }));
}

console.log(solution(["apple", null, "banana"]));`;
    }

    const textMessage: AIMessage = {
      id: (Date.now() + 1).toString(),
      role: 'assistant',
      content: `Here's a classic solution for your request using **${model}**:`,
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, textMessage]);

    await new Promise((resolve) => setTimeout(resolve, 500));

    const codeMessage: AIMessage = {
      id: (Date.now() + 2).toString(),
      role: 'assistant',
      content: responseContent,
      isCode: true,
      language: language,
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, codeMessage]);
    setIsGenerating(false);
  };

  const handleReset = () => {
    setMessages([]);
  };

  return (
    <div className="max-w-7xl mx-auto">
      {/* Header - same as dashboard */}
      <UserHeader name="Emad" badge="Developer" compact />
      <div className="h-px bg-gray-300 mb-6 md:mb-8" />

      {messages.length === 0 ? (
        <AIPromptEmptyState
          onGenerate={handleGenerate}
          selectedModel={selectedModel}
          onModelSelect={setSelectedModel}
        />
      ) : (
        <AIChatInterface
          messages={messages}
          isGenerating={isGenerating}
          onGenerate={handleGenerate}
          selectedModel={selectedModel}
          onModelSelect={setSelectedModel}
          onReset={handleReset}
        />
      )}
    </div>
  );
}
