'use client';

import React, { useState } from 'react';
import { AIMessage } from '@/types/ai';
import { useAvatar } from '@/store/useAvatarStore';
import Image from 'next/image';
import { Copy, Check, Terminal, Edit2 } from 'lucide-react';
import Editor from '@monaco-editor/react';

interface MessageBubbleProps {
  message: AIMessage;
}

export function MessageBubble({ message }: MessageBubbleProps) {
  const { avatar } = useAvatar();
  const isUser = message.role === 'user';
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(message.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className={`flex w-full ${isUser ? 'justify-end' : 'justify-start'} mb-6`}>
      <div className={`flex gap-3 max-w-[85%] ${isUser ? 'flex-row-reverse' : 'flex-row'}`}>

        {/* Avatar */}
        <div className="flex-shrink-0 mt-1">
          {isUser ? (
            <div className="w-9 h-9 rounded-full overflow-hidden border-2 border-gray-200 shadow-sm">
              <Image
                src={avatar}
                alt="User"
                width={36}
                height={36}
                className="object-cover w-full h-full"
              />
            </div>
          ) : (
            <div className="w-9 h-9 rounded-full bg-[#103B40] flex items-center justify-center shadow-sm">
              <Terminal className="w-4 h-4 text-white" />
            </div>
          )}
        </div>

        {/* Message Content */}
        <div className="flex flex-col gap-1.5 min-w-0 flex-1">
          {!isUser && (
            <span className="text-xs font-semibold text-[#103B40] ml-1">
              Thalorix-X Vision
            </span>
          )}

          {isUser ? (
            <div className="bg-[#103B40] text-white px-4 py-2.5 rounded-2xl rounded-tr-md text-sm shadow-sm leading-relaxed">
              {message.content}
            </div>
          ) : (
            <div className="w-full">
              {!message.isCode && (
                <div className="bg-white border border-gray-200 rounded-2xl rounded-tl-md px-4 py-2.5 text-sm text-gray-700 shadow-sm leading-relaxed">
                  {message.content}
                </div>
              )}

              {message.isCode && (
                <div className="rounded-xl overflow-hidden border border-gray-200 shadow-sm">
                  {/* Code Header */}
                  <div className="flex items-center justify-between px-4 py-2 bg-[#103B40]">
                    <div className="flex items-center gap-2">
                      <Terminal className="w-3.5 h-3.5 text-teal-300" />
                      <span className="text-xs font-medium text-white/90">
                        solution.{message.language === 'javascript' ? 'js' : message.language === 'python' ? 'py' : message.language === 'html' ? 'html' : 'ts'}
                      </span>
                      <span className="text-[10px] text-white/50 ml-1">Generated by Thalorix-X Vision</span>
                    </div>
                    <div className="flex items-center gap-1">
                      <button className="flex items-center gap-1 px-2 py-1 hover:bg-white/10 rounded text-[11px] text-white/70 hover:text-white transition-colors">
                        <Edit2 className="w-3 h-3" /> Edit
                      </button>
                      <button
                        onClick={handleCopy}
                        className="flex items-center gap-1 px-2 py-1 hover:bg-white/10 rounded text-[11px] text-white/70 hover:text-white transition-colors"
                      >
                        {copied ? <Check className="w-3 h-3 text-teal-300" /> : <Copy className="w-3 h-3" />}
                        {copied ? 'Copied' : 'Copy'}
                      </button>
                    </div>
                  </div>

                  {/* Code Body */}
                  <div className="bg-[#1e1e1e]">
                    <Editor
                      height={`${Math.min(Math.max(message.content.split('\n').length * 21, 100), 500)}px`}
                      language={message.language || 'javascript'}
                      theme="vs-dark"
                      value={message.content}
                      options={{
                        readOnly: true,
                        minimap: { enabled: false },
                        scrollBeyondLastLine: false,
                        fontSize: 13,
                        fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
                        padding: { top: 12, bottom: 12 },
                        lineHeight: 21,
                        renderLineHighlight: 'none',
                        scrollbar: {
                          vertical: 'hidden',
                          horizontal: 'hidden',
                        },
                      }}
                    />
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
